In [302]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Frank", "Grace", "Hannah","Sakib"],
    "City": ["New York", "Los Angeles", "Newark", "Boston", "New Delhi", "Chicago", "New Orleans", "Houston","H Los Ang"],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "Marketing", "Finance", "HR", "HR"],
    "Salary": [50000, 60000, 55000, 70000, 52000, 58000, 62000, 51000,70000]
}

df = pd.DataFrame(data)

In [303]:
df

      Name         City Department  Salary
0    Alice     New York         HR   50000
1      Bob  Los Angeles         IT   60000
2  Charlie       Newark    Finance   55000
3    David       Boston         IT   70000
4      Eve    New Delhi         HR   52000
5    Frank      Chicago  Marketing   58000
6    Grace  New Orleans    Finance   62000
7   Hannah      Houston         HR   51000
8    Sakib    H Los Ang         HR   70000

In [304]:
df.loc[df['City'].str.contains('Los')]

    Name         City Department  Salary
1    Bob  Los Angeles         IT   60000
8  Sakib    H Los Ang         HR   70000

In [305]:
df.loc[df['City'].str.contains('los', case=False)]

    Name         City Department  Salary
1    Bob  Los Angeles         IT   60000
8  Sakib    H Los Ang         HR   70000

In [306]:
# just starts with Los

df.loc[df['City'].str.contains(r"^Los")]

  Name         City Department  Salary
1  Bob  Los Angeles         IT   60000

In [307]:
df.loc[df['City'].str.contains(r"rk$")]

      Name      City Department  Salary
0    Alice  New York         HR   50000
2  Charlie    Newark    Finance   55000

In [308]:
# name starts with a vowel 

df.loc[df['Name'].str.contains(r"^[AEIOU]")]

    Name       City Department  Salary
0  Alice   New York         HR   50000
4    Eve  New Delhi         HR   52000

In [309]:
# string contains New or Los

df.loc[df['City'].str.contains(r"New|Los")]

      Name         City Department  Salary
0    Alice     New York         HR   50000
1      Bob  Los Angeles         IT   60000
2  Charlie       Newark    Finance   55000
4      Eve    New Delhi         HR   52000
6    Grace  New Orleans    Finance   62000
8    Sakib    H Los Ang         HR   70000

## Adding New Colums

In [310]:
df = pd.read_csv('student_data.csv')

df

   StudentID          FullName  Data Structure Marks  ...  EnrollmentDate  Instructor    Location
0     PH1001       Alif Rahman                  85.0  ...      2024-01-15   Mr. Karim       Dhaka
1     PH1002     Fatima Akhter                  92.0  ...      2024-01-20   Ms. Salma  Chattogram
2     PH1003     Imran Hossain                  88.0  ...      2024-02-10   Mr. Karim       Dhaka
3     PH1004  Jannatul Ferdous                  78.0  ...      2024-02-12   Ms. Salma      Sylhet
4     PH1005       Kamal Uddin                   NaN  ...      2024-03-05   Mr. Karim  Chattogram
5     PH1006       Laila Begum                  75.0  ...      2024-03-08   Ms. Salma    Rajshahi
6     PH1007    Mahmudul Hasan                  80.0  ...      2024-04-01   Mr. Karim       Dhaka
7     PH1008       Nadia Islam                  81.0  ...      2024-04-22   Ms. Salma  Chattogram
8     PH1009        Omar Faruq                  72.0  ...      2024-05-16   Mr. David       Dhaka
9     PH1010      Priya Sharma                  89.0  ...      2024-05-20   Ms. Salma      Sylhet
10    PH1011      Rahim Sheikh                   NaN  ...      2024-06-11   Mr. Karim      Khulna
11    PH1012   Sadia Chowdhury                  85.0  ...      2024-06-14   Ms. Salma  Chattogram
12    PH1013      Tanvir Ahmed                  75.0  ...      2024-07-02   Mr. David       Dhaka
13    PH1014        Urmi Akter                   NaN  ...      2024-07-09   Ms. Salma    Rajshahi
14    PH1015      Wahiduzzaman                  86.0  ...      2024-08-18   Mr. Karim       Dhaka
15    PH1016      Ziaur Rahman                  94.0  ...      2024-08-21   Ms. Salma  Chattogram
16    PH1017       Afsana Mimi                  90.0  ...      2025-09-01   Mr. Karim       Dhaka
17    PH1018       Babul Ahmed                  88.0  ...      2025-09-05   Ms. Salma      Sylhet
18    PH1019      Faria Rahman                   NaN  ...      2025-09-15   Mr. David  Chattogram
19    PH1020        Nasir Khan                  86.0  ...      2025-10-02   Ms. Salma       Dhaka
20       NaN               NaN                   NaN  ...             NaN         NaN         NaN

[21 rows x 9 columns]

In [311]:
# adding a column with constant value 

df['Country'] = 'Bangladesh'

df

   StudentID          FullName  Data Structure Marks  Algorithm Marks  ...  EnrollmentDate Instructor    Location     Country
0     PH1001       Alif Rahman                  85.0             85.0  ...      2024-01-15  Mr. Karim       Dhaka  Bangladesh
1     PH1002     Fatima Akhter                  92.0             92.0  ...      2024-01-20  Ms. Salma  Chattogram  Bangladesh
2     PH1003     Imran Hossain                  88.0             88.0  ...      2024-02-10  Mr. Karim       Dhaka  Bangladesh
3     PH1004  Jannatul Ferdous                  78.0             78.0  ...      2024-02-12  Ms. Salma      Sylhet  Bangladesh
4     PH1005       Kamal Uddin                   NaN              NaN  ...      2024-03-05  Mr. Karim  Chattogram  Bangladesh
5     PH1006       Laila Begum                  75.0             75.0  ...      2024-03-08  Ms. Salma    Rajshahi  Bangladesh
6     PH1007    Mahmudul Hasan                  80.0             80.0  ...      2024-04-01  Mr. Karim       Dhaka  Bangladesh
7     PH1008       Nadia Islam                  81.0             81.0  ...      2024-04-22  Ms. Salma  Chattogram  Bangladesh
8     PH1009        Omar Faruq                  72.0             72.0  ...      2024-05-16  Mr. David       Dhaka  Bangladesh
9     PH1010      Priya Sharma                  89.0             89.0  ...      2024-05-20  Ms. Salma      Sylhet  Bangladesh
10    PH1011      Rahim Sheikh                   NaN              NaN  ...      2024-06-11  Mr. Karim      Khulna  Bangladesh
11    PH1012   Sadia Chowdhury                  85.0             85.0  ...      2024-06-14  Ms. Salma  Chattogram  Bangladesh
12    PH1013      Tanvir Ahmed                  75.0             75.0  ...      2024-07-02  Mr. David       Dhaka  Bangladesh
13    PH1014        Urmi Akter                   NaN              NaN  ...      2024-07-09  Ms. Salma    Rajshahi  Bangladesh
14    PH1015      Wahiduzzaman                  86.0             86.0  ...      2024-08-18  Mr. Karim       Dhaka  Bangladesh
15    PH1016      Ziaur Rahman                  94.0             94.0  ...      2024-08-21  Ms. Salma  Chattogram  Bangladesh
16    PH1017       Afsana Mimi                  90.0             90.0  ...      2025-09-01  Mr. Karim       Dhaka  Bangladesh
17    PH1018       Babul Ahmed                  88.0             88.0  ...      2025-09-05  Ms. Salma      Sylhet  Bangladesh
18    PH1019      Faria Rahman                   NaN              NaN  ...      2025-09-15  Mr. David  Chattogram  Bangladesh
19    PH1020        Nasir Khan                  86.0             86.0  ...      2025-10-02  Ms. Salma       Dhaka  Bangladesh
20       NaN               NaN                   NaN              NaN  ...             NaN        NaN         NaN  Bangladesh

[21 rows x 10 columns]

In [312]:
df['Total Marks'] = ((df['Data Structure Marks'] + df['Python Marks'] + df['Algorithm Marks']) / 3).round()
df

   StudentID          FullName  Data Structure Marks  Algorithm Marks  ...  Instructor    Location     Country Total Marks
0     PH1001       Alif Rahman                  85.0             85.0  ...   Mr. Karim       Dhaka  Bangladesh        86.0
1     PH1002     Fatima Akhter                  92.0             92.0  ...   Ms. Salma  Chattogram  Bangladesh         NaN
2     PH1003     Imran Hossain                  88.0             88.0  ...   Mr. Karim       Dhaka  Bangladesh        87.0
3     PH1004  Jannatul Ferdous                  78.0             78.0  ...   Ms. Salma      Sylhet  Bangladesh        79.0
4     PH1005       Kamal Uddin                   NaN              NaN  ...   Mr. Karim  Chattogram  Bangladesh         NaN
5     PH1006       Laila Begum                  75.0             75.0  ...   Ms. Salma    Rajshahi  Bangladesh        76.0
6     PH1007    Mahmudul Hasan                  80.0             80.0  ...   Mr. Karim       Dhaka  Bangladesh         NaN
7     PH1008       Nadia Islam                  81.0             81.0  ...   Ms. Salma  Chattogram  Bangladesh        82.0
8     PH1009        Omar Faruq                  72.0             72.0  ...   Mr. David       Dhaka  Bangladesh        73.0
9     PH1010      Priya Sharma                  89.0             89.0  ...   Ms. Salma      Sylhet  Bangladesh        89.0
10    PH1011      Rahim Sheikh                   NaN              NaN  ...   Mr. Karim      Khulna  Bangladesh         NaN
11    PH1012   Sadia Chowdhury                  85.0             85.0  ...   Ms. Salma  Chattogram  Bangladesh        86.0
12    PH1013      Tanvir Ahmed                  75.0             75.0  ...   Mr. David       Dhaka  Bangladesh        76.0
13    PH1014        Urmi Akter                   NaN              NaN  ...   Ms. Salma    Rajshahi  Bangladesh         NaN
14    PH1015      Wahiduzzaman                  86.0             86.0  ...   Mr. Karim       Dhaka  Bangladesh        85.0
15    PH1016      Ziaur Rahman                  94.0             94.0  ...   Ms. Salma  Chattogram  Bangladesh         NaN
16    PH1017       Afsana Mimi                  90.0             90.0  ...   Mr. Karim       Dhaka  Bangladesh        91.0
17    PH1018       Babul Ahmed                  88.0             88.0  ...   Ms. Salma      Sylhet  Bangladesh        87.0
18    PH1019      Faria Rahman                   NaN              NaN  ...   Mr. David  Chattogram  Bangladesh         NaN
19    PH1020        Nasir Khan                  86.0             86.0  ...   Ms. Salma       Dhaka  Bangladesh        87.0
20       NaN               NaN                   NaN              NaN  ...         NaN         NaN  Bangladesh         NaN

[21 rows x 11 columns]

In [313]:
import numpy as np

In [314]:
df['grade marks'] = np.where(df['Total Marks'] >= 80, 'A+', np.where(df['Total Marks'] >= 70, 'A', 'F'))

df

   StudentID          FullName  Data Structure Marks  Algorithm Marks  ...    Location     Country Total Marks grade marks
0     PH1001       Alif Rahman                  85.0             85.0  ...       Dhaka  Bangladesh        86.0          A+
1     PH1002     Fatima Akhter                  92.0             92.0  ...  Chattogram  Bangladesh         NaN           F
2     PH1003     Imran Hossain                  88.0             88.0  ...       Dhaka  Bangladesh        87.0          A+
3     PH1004  Jannatul Ferdous                  78.0             78.0  ...      Sylhet  Bangladesh        79.0           A
4     PH1005       Kamal Uddin                   NaN              NaN  ...  Chattogram  Bangladesh         NaN           F
5     PH1006       Laila Begum                  75.0             75.0  ...    Rajshahi  Bangladesh        76.0           A
6     PH1007    Mahmudul Hasan                  80.0             80.0  ...       Dhaka  Bangladesh         NaN           F
7     PH1008       Nadia Islam                  81.0             81.0  ...  Chattogram  Bangladesh        82.0          A+
8     PH1009        Omar Faruq                  72.0             72.0  ...       Dhaka  Bangladesh        73.0           A
9     PH1010      Priya Sharma                  89.0             89.0  ...      Sylhet  Bangladesh        89.0          A+
10    PH1011      Rahim Sheikh                   NaN              NaN  ...      Khulna  Bangladesh         NaN           F
11    PH1012   Sadia Chowdhury                  85.0             85.0  ...  Chattogram  Bangladesh        86.0          A+
12    PH1013      Tanvir Ahmed                  75.0             75.0  ...       Dhaka  Bangladesh        76.0           A
13    PH1014        Urmi Akter                   NaN              NaN  ...    Rajshahi  Bangladesh         NaN           F
14    PH1015      Wahiduzzaman                  86.0             86.0  ...       Dhaka  Bangladesh        85.0          A+
15    PH1016      Ziaur Rahman                  94.0             94.0  ...  Chattogram  Bangladesh         NaN           F
16    PH1017       Afsana Mimi                  90.0             90.0  ...       Dhaka  Bangladesh        91.0          A+
17    PH1018       Babul Ahmed                  88.0             88.0  ...      Sylhet  Bangladesh        87.0          A+
18    PH1019      Faria Rahman                   NaN              NaN  ...  Chattogram  Bangladesh         NaN           F
19    PH1020        Nasir Khan                  86.0             86.0  ...       Dhaka  Bangladesh        87.0          A+
20       NaN               NaN                   NaN              NaN  ...         NaN  Bangladesh         NaN           F

[21 rows x 12 columns]

In [315]:
df['Is Passed?'] = df['Total Marks'] > 70

df

   StudentID          FullName  Data Structure Marks  Algorithm Marks  ...     Country Total Marks grade marks Is Passed?
0     PH1001       Alif Rahman                  85.0             85.0  ...  Bangladesh        86.0          A+       True
1     PH1002     Fatima Akhter                  92.0             92.0  ...  Bangladesh         NaN           F      False
2     PH1003     Imran Hossain                  88.0             88.0  ...  Bangladesh        87.0          A+       True
3     PH1004  Jannatul Ferdous                  78.0             78.0  ...  Bangladesh        79.0           A       True
4     PH1005       Kamal Uddin                   NaN              NaN  ...  Bangladesh         NaN           F      False
5     PH1006       Laila Begum                  75.0             75.0  ...  Bangladesh        76.0           A       True
6     PH1007    Mahmudul Hasan                  80.0             80.0  ...  Bangladesh         NaN           F      False
7     PH1008       Nadia Islam                  81.0             81.0  ...  Bangladesh        82.0          A+       True
8     PH1009        Omar Faruq                  72.0             72.0  ...  Bangladesh        73.0           A       True
9     PH1010      Priya Sharma                  89.0             89.0  ...  Bangladesh        89.0          A+       True
10    PH1011      Rahim Sheikh                   NaN              NaN  ...  Bangladesh         NaN           F      False
11    PH1012   Sadia Chowdhury                  85.0             85.0  ...  Bangladesh        86.0          A+       True
12    PH1013      Tanvir Ahmed                  75.0             75.0  ...  Bangladesh        76.0           A       True
13    PH1014        Urmi Akter                   NaN              NaN  ...  Bangladesh         NaN           F      False
14    PH1015      Wahiduzzaman                  86.0             86.0  ...  Bangladesh        85.0          A+       True
15    PH1016      Ziaur Rahman                  94.0             94.0  ...  Bangladesh         NaN           F      False
16    PH1017       Afsana Mimi                  90.0             90.0  ...  Bangladesh        91.0          A+       True
17    PH1018       Babul Ahmed                  88.0             88.0  ...  Bangladesh        87.0          A+       True
18    PH1019      Faria Rahman                   NaN              NaN  ...  Bangladesh         NaN           F      False
19    PH1020        Nasir Khan                  86.0             86.0  ...  Bangladesh        87.0          A+       True
20       NaN               NaN                   NaN              NaN  ...  Bangladesh         NaN           F      False

[21 rows x 13 columns]

In [316]:
df['First Name'] = df['FullName'].str.split(' ').str[0]

df

   StudentID          FullName  Data Structure Marks  ...  grade marks  Is Passed?    First Name
0     PH1001       Alif Rahman                  85.0  ...           A+        True          Alif
1     PH1002     Fatima Akhter                  92.0  ...            F       False        Fatima
2     PH1003     Imran Hossain                  88.0  ...           A+        True         Imran
3     PH1004  Jannatul Ferdous                  78.0  ...            A        True      Jannatul
4     PH1005       Kamal Uddin                   NaN  ...            F       False         Kamal
5     PH1006       Laila Begum                  75.0  ...            A        True         Laila
6     PH1007    Mahmudul Hasan                  80.0  ...            F       False      Mahmudul
7     PH1008       Nadia Islam                  81.0  ...           A+        True         Nadia
8     PH1009        Omar Faruq                  72.0  ...            A        True          Omar
9     PH1010      Priya Sharma                  89.0  ...           A+        True         Priya
10    PH1011      Rahim Sheikh                   NaN  ...            F       False         Rahim
11    PH1012   Sadia Chowdhury                  85.0  ...           A+        True         Sadia
12    PH1013      Tanvir Ahmed                  75.0  ...            A        True        Tanvir
13    PH1014        Urmi Akter                   NaN  ...            F       False          Urmi
14    PH1015      Wahiduzzaman                  86.0  ...           A+        True  Wahiduzzaman
15    PH1016      Ziaur Rahman                  94.0  ...            F       False         Ziaur
16    PH1017       Afsana Mimi                  90.0  ...           A+        True        Afsana
17    PH1018       Babul Ahmed                  88.0  ...           A+        True         Babul
18    PH1019      Faria Rahman                   NaN  ...            F       False         Faria
19    PH1020        Nasir Khan                  86.0  ...           A+        True         Nasir
20       NaN               NaN                   NaN  ...            F       False           NaN

[21 rows x 14 columns]

In [317]:
df1 = pd.read_csv('student_data.csv')
df1

   StudentID          FullName  Data Structure Marks  ...  EnrollmentDate  Instructor    Location
0     PH1001       Alif Rahman                  85.0  ...      2024-01-15   Mr. Karim       Dhaka
1     PH1002     Fatima Akhter                  92.0  ...      2024-01-20   Ms. Salma  Chattogram
2     PH1003     Imran Hossain                  88.0  ...      2024-02-10   Mr. Karim       Dhaka
3     PH1004  Jannatul Ferdous                  78.0  ...      2024-02-12   Ms. Salma      Sylhet
4     PH1005       Kamal Uddin                   NaN  ...      2024-03-05   Mr. Karim  Chattogram
5     PH1006       Laila Begum                  75.0  ...      2024-03-08   Ms. Salma    Rajshahi
6     PH1007    Mahmudul Hasan                  80.0  ...      2024-04-01   Mr. Karim       Dhaka
7     PH1008       Nadia Islam                  81.0  ...      2024-04-22   Ms. Salma  Chattogram
8     PH1009        Omar Faruq                  72.0  ...      2024-05-16   Mr. David       Dhaka
9     PH1010      Priya Sharma                  89.0  ...      2024-05-20   Ms. Salma      Sylhet
10    PH1011      Rahim Sheikh                   NaN  ...      2024-06-11   Mr. Karim      Khulna
11    PH1012   Sadia Chowdhury                  85.0  ...      2024-06-14   Ms. Salma  Chattogram
12    PH1013      Tanvir Ahmed                  75.0  ...      2024-07-02   Mr. David       Dhaka
13    PH1014        Urmi Akter                   NaN  ...      2024-07-09   Ms. Salma    Rajshahi
14    PH1015      Wahiduzzaman                  86.0  ...      2024-08-18   Mr. Karim       Dhaka
15    PH1016      Ziaur Rahman                  94.0  ...      2024-08-21   Ms. Salma  Chattogram
16    PH1017       Afsana Mimi                  90.0  ...      2025-09-01   Mr. Karim       Dhaka
17    PH1018       Babul Ahmed                  88.0  ...      2025-09-05   Ms. Salma      Sylhet
18    PH1019      Faria Rahman                   NaN  ...      2025-09-15   Mr. David  Chattogram
19    PH1020        Nasir Khan                  86.0  ...      2025-10-02   Ms. Salma       Dhaka
20       NaN               NaN                   NaN  ...             NaN         NaN         NaN

[21 rows x 9 columns]

In [318]:
df.to_csv('new_data.csv')

## Unique and nunique

In [319]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "Alice", "David", "Bob"],
    "City": ["New York", "London", "Paris", "New York", "Tokyo", "London"],
    "Score": [85, 90, 78, 85, 95, 90]
}

df = pd.DataFrame(data)
df

      Name      City  Score
0    Alice  New York     85
1      Bob    London     90
2  Charlie     Paris     78
3    Alice  New York     85
4    David     Tokyo     95
5      Bob    London     90

In [320]:
# unique works on only series with NULL values 
df['Name'].unique()

array(['Alice', 'Bob', 'Charlie', 'David'], dtype=object)

In [321]:
df1 = pd.read_csv('student_data.csv')

df1

   StudentID          FullName  Data Structure Marks  ...  EnrollmentDate  Instructor    Location
0     PH1001       Alif Rahman                  85.0  ...      2024-01-15   Mr. Karim       Dhaka
1     PH1002     Fatima Akhter                  92.0  ...      2024-01-20   Ms. Salma  Chattogram
2     PH1003     Imran Hossain                  88.0  ...      2024-02-10   Mr. Karim       Dhaka
3     PH1004  Jannatul Ferdous                  78.0  ...      2024-02-12   Ms. Salma      Sylhet
4     PH1005       Kamal Uddin                   NaN  ...      2024-03-05   Mr. Karim  Chattogram
5     PH1006       Laila Begum                  75.0  ...      2024-03-08   Ms. Salma    Rajshahi
6     PH1007    Mahmudul Hasan                  80.0  ...      2024-04-01   Mr. Karim       Dhaka
7     PH1008       Nadia Islam                  81.0  ...      2024-04-22   Ms. Salma  Chattogram
8     PH1009        Omar Faruq                  72.0  ...      2024-05-16   Mr. David       Dhaka
9     PH1010      Priya Sharma                  89.0  ...      2024-05-20   Ms. Salma      Sylhet
10    PH1011      Rahim Sheikh                   NaN  ...      2024-06-11   Mr. Karim      Khulna
11    PH1012   Sadia Chowdhury                  85.0  ...      2024-06-14   Ms. Salma  Chattogram
12    PH1013      Tanvir Ahmed                  75.0  ...      2024-07-02   Mr. David       Dhaka
13    PH1014        Urmi Akter                   NaN  ...      2024-07-09   Ms. Salma    Rajshahi
14    PH1015      Wahiduzzaman                  86.0  ...      2024-08-18   Mr. Karim       Dhaka
15    PH1016      Ziaur Rahman                  94.0  ...      2024-08-21   Ms. Salma  Chattogram
16    PH1017       Afsana Mimi                  90.0  ...      2025-09-01   Mr. Karim       Dhaka
17    PH1018       Babul Ahmed                  88.0  ...      2025-09-05   Ms. Salma      Sylhet
18    PH1019      Faria Rahman                   NaN  ...      2025-09-15   Mr. David  Chattogram
19    PH1020        Nasir Khan                  86.0  ...      2025-10-02   Ms. Salma       Dhaka
20       NaN               NaN                   NaN  ...             NaN         NaN         NaN

[21 rows x 9 columns]

In [322]:
# nunique works on DataFrame or series without NULL values 
print(len(df1['Data Structure Marks'].unique()))

df1['Data Structure Marks'].nunique()

13

12

## Check NULL

In [323]:
df1.isnull()

    StudentID  FullName  Data Structure Marks  Algorithm Marks  ...  CompletionStatus  EnrollmentDate  Instructor  Location
0       False     False                 False            False  ...             False           False       False     False
1       False     False                 False            False  ...             False           False       False     False
2       False     False                 False            False  ...             False           False       False     False
3       False     False                 False            False  ...             False           False       False     False
4       False     False                  True             True  ...             False           False       False     False
5       False     False                 False            False  ...             False           False       False     False
6       False     False                 False            False  ...             False           False       False     False
7       False     False                 False            False  ...             False           False       False     False
8       False     False                 False            False  ...             False           False       False     False
9       False     False                 False            False  ...             False           False       False     False
10      False     False                  True             True  ...             False           False       False     False
11      False     False                 False            False  ...             False           False       False     False
12      False     False                 False            False  ...             False           False       False     False
13      False     False                  True             True  ...             False           False       False     False
14      False     False                 False            False  ...             False           False       False     False
15      False     False                 False            False  ...             False           False       False     False
16      False     False                 False            False  ...             False           False       False     False
17      False     False                 False            False  ...             False           False       False     False
18      False     False                  True             True  ...             False           False       False     False
19      False     False                 False            False  ...             False           False       False     False
20       True      True                  True             True  ...              True            True        True      True

[21 rows x 9 columns]

In [324]:
df1['Data Structure Marks'].isnull()

0     False
1     False
2     False
3     False
4      True
5     False
6     False
7     False
8     False
9     False
10     True
11    False
12    False
13     True
14    False
15    False
16    False
17    False
18     True
19    False
20     True
Name: Data Structure Marks, dtype: bool

In [325]:
df1.notnull()

df1['Data Structure Marks'].notnull()

0      True
1      True
2      True
3      True
4     False
5      True
6      True
7      True
8      True
9      True
10    False
11     True
12     True
13    False
14     True
15     True
16     True
17     True
18    False
19     True
20    False
Name: Data Structure Marks, dtype: bool

In [326]:
df1['Data Structure Marks'].hasnans

True

In [327]:
df1['StudentID'].hasnans

True

## Handling Duplicates Values

In [328]:
import pandas as pd
data = {
    "Name": ["Alice", "Bob", "Charlie", "Alice", "David", "Bob"],
    "City": ["New York", "London", "Paris", "New York", "Tokyo", "London"],
    "Score": [85, 90, 78, 70, 95, 90]
}

df = pd.DataFrame(data)
df

      Name      City  Score
0    Alice  New York     85
1      Bob    London     90
2  Charlie     Paris     78
3    Alice  New York     70
4    David     Tokyo     95
5      Bob    London     90

In [329]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5     True
dtype: bool

In [330]:
df.duplicated().sum()

np.int64(1)

In [331]:
delete_dup = df.drop_duplicates()

delete_dup

      Name      City  Score
0    Alice  New York     85
1      Bob    London     90
2  Charlie     Paris     78
3    Alice  New York     70
4    David     Tokyo     95

In [332]:
df.drop_duplicates(inplace=True)

df

      Name      City  Score
0    Alice  New York     85
1      Bob    London     90
2  Charlie     Paris     78
3    Alice  New York     70
4    David     Tokyo     95

In [333]:
# name er basis e duplicate deletion 

df.drop_duplicates(subset=['Name'])

      Name      City  Score
0    Alice  New York     85
1      Bob    London     90
2  Charlie     Paris     78
4    David     Tokyo     95

In [334]:
df.drop_duplicates(subset=['Name', 'City'])

      Name      City  Score
0    Alice  New York     85
1      Bob    London     90
2  Charlie     Paris     78
4    David     Tokyo     95

In [335]:
df.drop_duplicates(subset=['Name', 'City'], keep='last')

      Name      City  Score
1      Bob    London     90
2  Charlie     Paris     78
3    Alice  New York     70
4    David     Tokyo     95

In [336]:
df = pd.read_csv('student_data.csv')

df

   StudentID          FullName  Data Structure Marks  ...  EnrollmentDate  Instructor    Location
0     PH1001       Alif Rahman                  85.0  ...      2024-01-15   Mr. Karim       Dhaka
1     PH1002     Fatima Akhter                  92.0  ...      2024-01-20   Ms. Salma  Chattogram
2     PH1003     Imran Hossain                  88.0  ...      2024-02-10   Mr. Karim       Dhaka
3     PH1004  Jannatul Ferdous                  78.0  ...      2024-02-12   Ms. Salma      Sylhet
4     PH1005       Kamal Uddin                   NaN  ...      2024-03-05   Mr. Karim  Chattogram
5     PH1006       Laila Begum                  75.0  ...      2024-03-08   Ms. Salma    Rajshahi
6     PH1007    Mahmudul Hasan                  80.0  ...      2024-04-01   Mr. Karim       Dhaka
7     PH1008       Nadia Islam                  81.0  ...      2024-04-22   Ms. Salma  Chattogram
8     PH1009        Omar Faruq                  72.0  ...      2024-05-16   Mr. David       Dhaka
9     PH1010      Priya Sharma                  89.0  ...      2024-05-20   Ms. Salma      Sylhet
10    PH1011      Rahim Sheikh                   NaN  ...      2024-06-11   Mr. Karim      Khulna
11    PH1012   Sadia Chowdhury                  85.0  ...      2024-06-14   Ms. Salma  Chattogram
12    PH1013      Tanvir Ahmed                  75.0  ...      2024-07-02   Mr. David       Dhaka
13    PH1014        Urmi Akter                   NaN  ...      2024-07-09   Ms. Salma    Rajshahi
14    PH1015      Wahiduzzaman                  86.0  ...      2024-08-18   Mr. Karim       Dhaka
15    PH1016      Ziaur Rahman                  94.0  ...      2024-08-21   Ms. Salma  Chattogram
16    PH1017       Afsana Mimi                  90.0  ...      2025-09-01   Mr. Karim       Dhaka
17    PH1018       Babul Ahmed                  88.0  ...      2025-09-05   Ms. Salma      Sylhet
18    PH1019      Faria Rahman                   NaN  ...      2025-09-15   Mr. David  Chattogram
19    PH1020        Nasir Khan                  86.0  ...      2025-10-02   Ms. Salma       Dhaka
20       NaN               NaN                   NaN  ...             NaN         NaN         NaN

[21 rows x 9 columns]

In [337]:
# delete NULL from dataframe

df.dropna()

   StudentID          FullName  Data Structure Marks  ...  EnrollmentDate  Instructor    Location
0     PH1001       Alif Rahman                  85.0  ...      2024-01-15   Mr. Karim       Dhaka
2     PH1003     Imran Hossain                  88.0  ...      2024-02-10   Mr. Karim       Dhaka
3     PH1004  Jannatul Ferdous                  78.0  ...      2024-02-12   Ms. Salma      Sylhet
5     PH1006       Laila Begum                  75.0  ...      2024-03-08   Ms. Salma    Rajshahi
7     PH1008       Nadia Islam                  81.0  ...      2024-04-22   Ms. Salma  Chattogram
8     PH1009        Omar Faruq                  72.0  ...      2024-05-16   Mr. David       Dhaka
9     PH1010      Priya Sharma                  89.0  ...      2024-05-20   Ms. Salma      Sylhet
11    PH1012   Sadia Chowdhury                  85.0  ...      2024-06-14   Ms. Salma  Chattogram
12    PH1013      Tanvir Ahmed                  75.0  ...      2024-07-02   Mr. David       Dhaka
14    PH1015      Wahiduzzaman                  86.0  ...      2024-08-18   Mr. Karim       Dhaka
16    PH1017       Afsana Mimi                  90.0  ...      2025-09-01   Mr. Karim       Dhaka
17    PH1018       Babul Ahmed                  88.0  ...      2025-09-05   Ms. Salma      Sylhet
19    PH1020        Nasir Khan                  86.0  ...      2025-10-02   Ms. Salma       Dhaka

[13 rows x 9 columns]

In [338]:
df.dropna(how='all', inplace=True)    # delete full row if row all value is NULL

In [339]:
df.dropna(subset=['Python Marks'])

   StudentID          FullName  Data Structure Marks  ...  EnrollmentDate  Instructor    Location
0     PH1001       Alif Rahman                  85.0  ...      2024-01-15   Mr. Karim       Dhaka
2     PH1003     Imran Hossain                  88.0  ...      2024-02-10   Mr. Karim       Dhaka
3     PH1004  Jannatul Ferdous                  78.0  ...      2024-02-12   Ms. Salma      Sylhet
4     PH1005       Kamal Uddin                   NaN  ...      2024-03-05   Mr. Karim  Chattogram
5     PH1006       Laila Begum                  75.0  ...      2024-03-08   Ms. Salma    Rajshahi
7     PH1008       Nadia Islam                  81.0  ...      2024-04-22   Ms. Salma  Chattogram
8     PH1009        Omar Faruq                  72.0  ...      2024-05-16   Mr. David       Dhaka
9     PH1010      Priya Sharma                  89.0  ...      2024-05-20   Ms. Salma      Sylhet
10    PH1011      Rahim Sheikh                   NaN  ...      2024-06-11   Mr. Karim      Khulna
11    PH1012   Sadia Chowdhury                  85.0  ...      2024-06-14   Ms. Salma  Chattogram
12    PH1013      Tanvir Ahmed                  75.0  ...      2024-07-02   Mr. David       Dhaka
14    PH1015      Wahiduzzaman                  86.0  ...      2024-08-18   Mr. Karim       Dhaka
16    PH1017       Afsana Mimi                  90.0  ...      2025-09-01   Mr. Karim       Dhaka
17    PH1018       Babul Ahmed                  88.0  ...      2025-09-05   Ms. Salma      Sylhet
19    PH1020        Nasir Khan                  86.0  ...      2025-10-02   Ms. Salma       Dhaka

[15 rows x 9 columns]

In [340]:
df.dropna(subset=['Python Marks','Algorithm Marks'])

   StudentID          FullName  Data Structure Marks  ...  EnrollmentDate  Instructor    Location
0     PH1001       Alif Rahman                  85.0  ...      2024-01-15   Mr. Karim       Dhaka
2     PH1003     Imran Hossain                  88.0  ...      2024-02-10   Mr. Karim       Dhaka
3     PH1004  Jannatul Ferdous                  78.0  ...      2024-02-12   Ms. Salma      Sylhet
5     PH1006       Laila Begum                  75.0  ...      2024-03-08   Ms. Salma    Rajshahi
7     PH1008       Nadia Islam                  81.0  ...      2024-04-22   Ms. Salma  Chattogram
8     PH1009        Omar Faruq                  72.0  ...      2024-05-16   Mr. David       Dhaka
9     PH1010      Priya Sharma                  89.0  ...      2024-05-20   Ms. Salma      Sylhet
11    PH1012   Sadia Chowdhury                  85.0  ...      2024-06-14   Ms. Salma  Chattogram
12    PH1013      Tanvir Ahmed                  75.0  ...      2024-07-02   Mr. David       Dhaka
14    PH1015      Wahiduzzaman                  86.0  ...      2024-08-18   Mr. Karim       Dhaka
16    PH1017       Afsana Mimi                  90.0  ...      2025-09-01   Mr. Karim       Dhaka
17    PH1018       Babul Ahmed                  88.0  ...      2025-09-05   Ms. Salma      Sylhet
19    PH1020        Nasir Khan                  86.0  ...      2025-10-02   Ms. Salma       Dhaka

[13 rows x 9 columns]

In [341]:
df = pd.read_csv('student_data.csv')

df

   StudentID          FullName  Data Structure Marks  ...  EnrollmentDate  Instructor    Location
0     PH1001       Alif Rahman                  85.0  ...      2024-01-15   Mr. Karim       Dhaka
1     PH1002     Fatima Akhter                  92.0  ...      2024-01-20   Ms. Salma  Chattogram
2     PH1003     Imran Hossain                  88.0  ...      2024-02-10   Mr. Karim       Dhaka
3     PH1004  Jannatul Ferdous                  78.0  ...      2024-02-12   Ms. Salma      Sylhet
4     PH1005       Kamal Uddin                   NaN  ...      2024-03-05   Mr. Karim  Chattogram
5     PH1006       Laila Begum                  75.0  ...      2024-03-08   Ms. Salma    Rajshahi
6     PH1007    Mahmudul Hasan                  80.0  ...      2024-04-01   Mr. Karim       Dhaka
7     PH1008       Nadia Islam                  81.0  ...      2024-04-22   Ms. Salma  Chattogram
8     PH1009        Omar Faruq                  72.0  ...      2024-05-16   Mr. David       Dhaka
9     PH1010      Priya Sharma                  89.0  ...      2024-05-20   Ms. Salma      Sylhet
10    PH1011      Rahim Sheikh                   NaN  ...      2024-06-11   Mr. Karim      Khulna
11    PH1012   Sadia Chowdhury                  85.0  ...      2024-06-14   Ms. Salma  Chattogram
12    PH1013      Tanvir Ahmed                  75.0  ...      2024-07-02   Mr. David       Dhaka
13    PH1014        Urmi Akter                   NaN  ...      2024-07-09   Ms. Salma    Rajshahi
14    PH1015      Wahiduzzaman                  86.0  ...      2024-08-18   Mr. Karim       Dhaka
15    PH1016      Ziaur Rahman                  94.0  ...      2024-08-21   Ms. Salma  Chattogram
16    PH1017       Afsana Mimi                  90.0  ...      2025-09-01   Mr. Karim       Dhaka
17    PH1018       Babul Ahmed                  88.0  ...      2025-09-05   Ms. Salma      Sylhet
18    PH1019      Faria Rahman                   NaN  ...      2025-09-15   Mr. David  Chattogram
19    PH1020        Nasir Khan                  86.0  ...      2025-10-02   Ms. Salma       Dhaka
20       NaN               NaN                   NaN  ...             NaN         NaN         NaN

[21 rows x 9 columns]

In [342]:
df.fillna(0)

   StudentID          FullName  Data Structure Marks  ...  EnrollmentDate  Instructor    Location
0     PH1001       Alif Rahman                  85.0  ...      2024-01-15   Mr. Karim       Dhaka
1     PH1002     Fatima Akhter                  92.0  ...      2024-01-20   Ms. Salma  Chattogram
2     PH1003     Imran Hossain                  88.0  ...      2024-02-10   Mr. Karim       Dhaka
3     PH1004  Jannatul Ferdous                  78.0  ...      2024-02-12   Ms. Salma      Sylhet
4     PH1005       Kamal Uddin                   0.0  ...      2024-03-05   Mr. Karim  Chattogram
5     PH1006       Laila Begum                  75.0  ...      2024-03-08   Ms. Salma    Rajshahi
6     PH1007    Mahmudul Hasan                  80.0  ...      2024-04-01   Mr. Karim       Dhaka
7     PH1008       Nadia Islam                  81.0  ...      2024-04-22   Ms. Salma  Chattogram
8     PH1009        Omar Faruq                  72.0  ...      2024-05-16   Mr. David       Dhaka
9     PH1010      Priya Sharma                  89.0  ...      2024-05-20   Ms. Salma      Sylhet
10    PH1011      Rahim Sheikh                   0.0  ...      2024-06-11   Mr. Karim      Khulna
11    PH1012   Sadia Chowdhury                  85.0  ...      2024-06-14   Ms. Salma  Chattogram
12    PH1013      Tanvir Ahmed                  75.0  ...      2024-07-02   Mr. David       Dhaka
13    PH1014        Urmi Akter                   0.0  ...      2024-07-09   Ms. Salma    Rajshahi
14    PH1015      Wahiduzzaman                  86.0  ...      2024-08-18   Mr. Karim       Dhaka
15    PH1016      Ziaur Rahman                  94.0  ...      2024-08-21   Ms. Salma  Chattogram
16    PH1017       Afsana Mimi                  90.0  ...      2025-09-01   Mr. Karim       Dhaka
17    PH1018       Babul Ahmed                  88.0  ...      2025-09-05   Ms. Salma      Sylhet
18    PH1019      Faria Rahman                   0.0  ...      2025-09-15   Mr. David  Chattogram
19    PH1020        Nasir Khan                  86.0  ...      2025-10-02   Ms. Salma       Dhaka
20         0                 0                   0.0  ...               0           0           0

[21 rows x 9 columns]

In [343]:
df['FullName'].fillna('unknown')

0          Alif Rahman
1        Fatima Akhter
2        Imran Hossain
3     Jannatul Ferdous
4          Kamal Uddin
5          Laila Begum
6       Mahmudul Hasan
7          Nadia Islam
8           Omar Faruq
9         Priya Sharma
10        Rahim Sheikh
11     Sadia Chowdhury
12        Tanvir Ahmed
13          Urmi Akter
14        Wahiduzzaman
15        Ziaur Rahman
16         Afsana Mimi
17         Babul Ahmed
18        Faria Rahman
19          Nasir Khan
20             unknown
Name: FullName, dtype: object

In [344]:
df['Python Marks'].fillna(df['Python Marks'].mean().round(), inplace=True)

df

C:\Users\CTRL\AppData\Local\Temp\ipykernel_2568\1146547899.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Python Marks'].fillna(df['Python Marks'].mean().round(), inplace=True)

   StudentID          FullName  Data Structure Marks  ...  EnrollmentDate  Instructor    Location
0     PH1001       Alif Rahman                  85.0  ...      2024-01-15   Mr. Karim       Dhaka
1     PH1002     Fatima Akhter                  92.0  ...      2024-01-20   Ms. Salma  Chattogram
2     PH1003     Imran Hossain                  88.0  ...      2024-02-10   Mr. Karim       Dhaka
3     PH1004  Jannatul Ferdous                  78.0  ...      2024-02-12   Ms. Salma      Sylhet
4     PH1005       Kamal Uddin                   NaN  ...      2024-03-05   Mr. Karim  Chattogram
5     PH1006       Laila Begum                  75.0  ...      2024-03-08   Ms. Salma    Rajshahi
6     PH1007    Mahmudul Hasan                  80.0  ...      2024-04-01   Mr. Karim       Dhaka
7     PH1008       Nadia Islam                  81.0  ...      2024-04-22   Ms. Salma  Chattogram
8     PH1009        Omar Faruq                  72.0  ...      2024-05-16   Mr. David       Dhaka
9     PH1010      Priya Sharma                  89.0  ...      2024-05-20   Ms. Salma      Sylhet
10    PH1011      Rahim Sheikh                   NaN  ...      2024-06-11   Mr. Karim      Khulna
11    PH1012   Sadia Chowdhury                  85.0  ...      2024-06-14   Ms. Salma  Chattogram
12    PH1013      Tanvir Ahmed                  75.0  ...      2024-07-02   Mr. David       Dhaka
13    PH1014        Urmi Akter                   NaN  ...      2024-07-09   Ms. Salma    Rajshahi
14    PH1015      Wahiduzzaman                  86.0  ...      2024-08-18   Mr. Karim       Dhaka
15    PH1016      Ziaur Rahman                  94.0  ...      2024-08-21   Ms. Salma  Chattogram
16    PH1017       Afsana Mimi                  90.0  ...      2025-09-01   Mr. Karim       Dhaka
17    PH1018       Babul Ahmed                  88.0  ...      2025-09-05   Ms. Salma      Sylhet
18    PH1019      Faria Rahman                   NaN  ...      2025-09-15   Mr. David  Chattogram
19    PH1020        Nasir Khan                  86.0  ...      2025-10-02   Ms. Salma       Dhaka
20       NaN               NaN                   NaN  ...             NaN         NaN         NaN

[21 rows x 9 columns]

## Statistical Functions

In [345]:
df

   StudentID          FullName  Data Structure Marks  ...  EnrollmentDate  Instructor    Location
0     PH1001       Alif Rahman                  85.0  ...      2024-01-15   Mr. Karim       Dhaka
1     PH1002     Fatima Akhter                  92.0  ...      2024-01-20   Ms. Salma  Chattogram
2     PH1003     Imran Hossain                  88.0  ...      2024-02-10   Mr. Karim       Dhaka
3     PH1004  Jannatul Ferdous                  78.0  ...      2024-02-12   Ms. Salma      Sylhet
4     PH1005       Kamal Uddin                   NaN  ...      2024-03-05   Mr. Karim  Chattogram
5     PH1006       Laila Begum                  75.0  ...      2024-03-08   Ms. Salma    Rajshahi
6     PH1007    Mahmudul Hasan                  80.0  ...      2024-04-01   Mr. Karim       Dhaka
7     PH1008       Nadia Islam                  81.0  ...      2024-04-22   Ms. Salma  Chattogram
8     PH1009        Omar Faruq                  72.0  ...      2024-05-16   Mr. David       Dhaka
9     PH1010      Priya Sharma                  89.0  ...      2024-05-20   Ms. Salma      Sylhet
10    PH1011      Rahim Sheikh                   NaN  ...      2024-06-11   Mr. Karim      Khulna
11    PH1012   Sadia Chowdhury                  85.0  ...      2024-06-14   Ms. Salma  Chattogram
12    PH1013      Tanvir Ahmed                  75.0  ...      2024-07-02   Mr. David       Dhaka
13    PH1014        Urmi Akter                   NaN  ...      2024-07-09   Ms. Salma    Rajshahi
14    PH1015      Wahiduzzaman                  86.0  ...      2024-08-18   Mr. Karim       Dhaka
15    PH1016      Ziaur Rahman                  94.0  ...      2024-08-21   Ms. Salma  Chattogram
16    PH1017       Afsana Mimi                  90.0  ...      2025-09-01   Mr. Karim       Dhaka
17    PH1018       Babul Ahmed                  88.0  ...      2025-09-05   Ms. Salma      Sylhet
18    PH1019      Faria Rahman                   NaN  ...      2025-09-15   Mr. David  Chattogram
19    PH1020        Nasir Khan                  86.0  ...      2025-10-02   Ms. Salma       Dhaka
20       NaN               NaN                   NaN  ...             NaN         NaN         NaN

[21 rows x 9 columns]

In [346]:
df.dropna()

   StudentID          FullName  Data Structure Marks  ...  EnrollmentDate  Instructor    Location
0     PH1001       Alif Rahman                  85.0  ...      2024-01-15   Mr. Karim       Dhaka
1     PH1002     Fatima Akhter                  92.0  ...      2024-01-20   Ms. Salma  Chattogram
2     PH1003     Imran Hossain                  88.0  ...      2024-02-10   Mr. Karim       Dhaka
3     PH1004  Jannatul Ferdous                  78.0  ...      2024-02-12   Ms. Salma      Sylhet
5     PH1006       Laila Begum                  75.0  ...      2024-03-08   Ms. Salma    Rajshahi
6     PH1007    Mahmudul Hasan                  80.0  ...      2024-04-01   Mr. Karim       Dhaka
7     PH1008       Nadia Islam                  81.0  ...      2024-04-22   Ms. Salma  Chattogram
8     PH1009        Omar Faruq                  72.0  ...      2024-05-16   Mr. David       Dhaka
9     PH1010      Priya Sharma                  89.0  ...      2024-05-20   Ms. Salma      Sylhet
11    PH1012   Sadia Chowdhury                  85.0  ...      2024-06-14   Ms. Salma  Chattogram
12    PH1013      Tanvir Ahmed                  75.0  ...      2024-07-02   Mr. David       Dhaka
14    PH1015      Wahiduzzaman                  86.0  ...      2024-08-18   Mr. Karim       Dhaka
15    PH1016      Ziaur Rahman                  94.0  ...      2024-08-21   Ms. Salma  Chattogram
16    PH1017       Afsana Mimi                  90.0  ...      2025-09-01   Mr. Karim       Dhaka
17    PH1018       Babul Ahmed                  88.0  ...      2025-09-05   Ms. Salma      Sylhet
19    PH1020        Nasir Khan                  86.0  ...      2025-10-02   Ms. Salma       Dhaka

[16 rows x 9 columns]

In [347]:
# sum
df['Data Structure Marks'].sum()

np.float64(1344.0)

In [348]:
# max and min 
print(df['Data Structure Marks'].min())
df['Data Structure Marks'].max()

72.0

94.0

In [349]:
#mean -> average 

df['Data Structure Marks'].mean()

np.float64(84.0)

In [350]:
#median -> middle value

df['Data Structure Marks'].median()

85.5

In [351]:
# mode -> highest frequency er number 

df['Data Structure Marks'].mode()

0    75.0
1    85.0
2    86.0
3    88.0
Name: Data Structure Marks, dtype: float64

In [352]:
# standard deviation -> std 
df['Data Structure Marks'].std()

6.501281924871945

In [353]:
# correlation matrix 

df[['Data Structure Marks','Python Marks']].corr()

                      Data Structure Marks  Python Marks
Data Structure Marks              1.000000      0.784992
Python Marks                      0.784992      1.000000

In [354]:
# sum in different columns row wise
df[['Data Structure Marks','Python Marks']].sum()

Data Structure Marks    1344.0
Python Marks            1801.0
dtype: float64

In [355]:
# sum in different columns column wise
df[['Data Structure Marks','Python Marks']].sum(axis=1)

0     173.0
1     178.0
2     173.0
3     160.0
4      95.0
5     153.0
6     166.0
7     166.0
8     148.0
9     177.0
10     91.0
11    172.0
12    154.0
13     86.0
14    170.0
15    180.0
16    183.0
17    173.0
18     86.0
19    175.0
20     86.0
dtype: float64

In [356]:
df['Total Marks'] = df.iloc[::,2:5].sum(axis=1) 

df

   StudentID          FullName  Data Structure Marks  ...  Instructor    Location Total Marks
0     PH1001       Alif Rahman                  85.0  ...   Mr. Karim       Dhaka       258.0
1     PH1002     Fatima Akhter                  92.0  ...   Ms. Salma  Chattogram       270.0
2     PH1003     Imran Hossain                  88.0  ...   Mr. Karim       Dhaka       261.0
3     PH1004  Jannatul Ferdous                  78.0  ...   Ms. Salma      Sylhet       238.0
4     PH1005       Kamal Uddin                   NaN  ...   Mr. Karim  Chattogram        95.0
5     PH1006       Laila Begum                  75.0  ...   Ms. Salma    Rajshahi       228.0
6     PH1007    Mahmudul Hasan                  80.0  ...   Mr. Karim       Dhaka       246.0
7     PH1008       Nadia Islam                  81.0  ...   Ms. Salma  Chattogram       247.0
8     PH1009        Omar Faruq                  72.0  ...   Mr. David       Dhaka       220.0
9     PH1010      Priya Sharma                  89.0  ...   Ms. Salma      Sylhet       266.0
10    PH1011      Rahim Sheikh                   NaN  ...   Mr. Karim      Khulna        91.0
11    PH1012   Sadia Chowdhury                  85.0  ...   Ms. Salma  Chattogram       257.0
12    PH1013      Tanvir Ahmed                  75.0  ...   Mr. David       Dhaka       229.0
13    PH1014        Urmi Akter                   NaN  ...   Ms. Salma    Rajshahi        86.0
14    PH1015      Wahiduzzaman                  86.0  ...   Mr. Karim       Dhaka       256.0
15    PH1016      Ziaur Rahman                  94.0  ...   Ms. Salma  Chattogram       274.0
16    PH1017       Afsana Mimi                  90.0  ...   Mr. Karim       Dhaka       273.0
17    PH1018       Babul Ahmed                  88.0  ...   Ms. Salma      Sylhet       261.0
18    PH1019      Faria Rahman                   NaN  ...   Mr. David  Chattogram        86.0
19    PH1020        Nasir Khan                  86.0  ...   Ms. Salma       Dhaka       261.0
20       NaN               NaN                   NaN  ...         NaN         NaN        86.0

[21 rows x 10 columns]

In [357]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   StudentID             20 non-null     object
 1   FullName              20 non-null     object
 2   Data Structure Marks  16 non-null     float64
 3   Algorithm Marks       16 non-null     float64
 4   Python Marks          21 non-null     float64
 5   CompletionStatus      20 non-null     object
 6   EnrollmentDate        20 non-null     object
 7   Instructor            20 non-null     object
 8   Location              20 non-null     object
 9   Total Marks           21 non-null     float64
dtypes: float64(4), object(6)
memory usage: 1.8+ KB

In [358]:
df.describe()

       Data Structure Marks  Algorithm Marks  Python Marks  Total Marks
count             16.000000        16.000000     21.000000    21.000000
mean              84.000000        84.000000     85.761905   213.761905
std                6.501282         6.501282      4.515581    73.035543
min               72.000000        72.000000     76.000000    86.000000
25%               79.500000        79.500000     85.000000   220.000000
50%               85.500000        85.500000     86.000000   247.000000
75%               88.250000        88.250000     88.000000   261.000000
max               94.000000        94.000000     95.000000   274.000000

## apply function on df

In [359]:
mn = df['Total Marks'].min()
mx = df['Total Marks'].max()

df['Scaled Marks'] = df['Total Marks'].apply(lambda x : (x - mn) / (mx - mn))

df

   StudentID          FullName  Data Structure Marks  Algorithm Marks  ...  Instructor    Location Total Marks Scaled Marks
0     PH1001       Alif Rahman                  85.0             85.0  ...   Mr. Karim       Dhaka       258.0     0.914894
1     PH1002     Fatima Akhter                  92.0             92.0  ...   Ms. Salma  Chattogram       270.0     0.978723
2     PH1003     Imran Hossain                  88.0             88.0  ...   Mr. Karim       Dhaka       261.0     0.930851
3     PH1004  Jannatul Ferdous                  78.0             78.0  ...   Ms. Salma      Sylhet       238.0     0.808511
4     PH1005       Kamal Uddin                   NaN              NaN  ...   Mr. Karim  Chattogram        95.0     0.047872
5     PH1006       Laila Begum                  75.0             75.0  ...   Ms. Salma    Rajshahi       228.0     0.755319
6     PH1007    Mahmudul Hasan                  80.0             80.0  ...   Mr. Karim       Dhaka       246.0     0.851064
7     PH1008       Nadia Islam                  81.0             81.0  ...   Ms. Salma  Chattogram       247.0     0.856383
8     PH1009        Omar Faruq                  72.0             72.0  ...   Mr. David       Dhaka       220.0     0.712766
9     PH1010      Priya Sharma                  89.0             89.0  ...   Ms. Salma      Sylhet       266.0     0.957447
10    PH1011      Rahim Sheikh                   NaN              NaN  ...   Mr. Karim      Khulna        91.0     0.026596
11    PH1012   Sadia Chowdhury                  85.0             85.0  ...   Ms. Salma  Chattogram       257.0     0.909574
12    PH1013      Tanvir Ahmed                  75.0             75.0  ...   Mr. David       Dhaka       229.0     0.760638
13    PH1014        Urmi Akter                   NaN              NaN  ...   Ms. Salma    Rajshahi        86.0     0.000000
14    PH1015      Wahiduzzaman                  86.0             86.0  ...   Mr. Karim       Dhaka       256.0     0.904255
15    PH1016      Ziaur Rahman                  94.0             94.0  ...   Ms. Salma  Chattogram       274.0     1.000000
16    PH1017       Afsana Mimi                  90.0             90.0  ...   Mr. Karim       Dhaka       273.0     0.994681
17    PH1018       Babul Ahmed                  88.0             88.0  ...   Ms. Salma      Sylhet       261.0     0.930851
18    PH1019      Faria Rahman                   NaN              NaN  ...   Mr. David  Chattogram        86.0     0.000000
19    PH1020        Nasir Khan                  86.0             86.0  ...   Ms. Salma       Dhaka       261.0     0.930851
20       NaN               NaN                   NaN              NaN  ...         NaN         NaN        86.0     0.000000

[21 rows x 11 columns]

In [360]:
# custom built function

def grading_system(mark):
    if mark >= 260:
        return 'A+'
    elif mark >= 250:
        return 'A'
    else:
        return 'A-'

df['Grade'] = df['Total Marks'].apply(grading_system)

df

   StudentID          FullName  Data Structure Marks  Algorithm Marks  ...    Location Total Marks Scaled Marks Grade
0     PH1001       Alif Rahman                  85.0             85.0  ...       Dhaka       258.0     0.914894     A
1     PH1002     Fatima Akhter                  92.0             92.0  ...  Chattogram       270.0     0.978723    A+
2     PH1003     Imran Hossain                  88.0             88.0  ...       Dhaka       261.0     0.930851    A+
3     PH1004  Jannatul Ferdous                  78.0             78.0  ...      Sylhet       238.0     0.808511    A-
4     PH1005       Kamal Uddin                   NaN              NaN  ...  Chattogram        95.0     0.047872    A-
5     PH1006       Laila Begum                  75.0             75.0  ...    Rajshahi       228.0     0.755319    A-
6     PH1007    Mahmudul Hasan                  80.0             80.0  ...       Dhaka       246.0     0.851064    A-
7     PH1008       Nadia Islam                  81.0             81.0  ...  Chattogram       247.0     0.856383    A-
8     PH1009        Omar Faruq                  72.0             72.0  ...       Dhaka       220.0     0.712766    A-
9     PH1010      Priya Sharma                  89.0             89.0  ...      Sylhet       266.0     0.957447    A+
10    PH1011      Rahim Sheikh                   NaN              NaN  ...      Khulna        91.0     0.026596    A-
11    PH1012   Sadia Chowdhury                  85.0             85.0  ...  Chattogram       257.0     0.909574     A
12    PH1013      Tanvir Ahmed                  75.0             75.0  ...       Dhaka       229.0     0.760638    A-
13    PH1014        Urmi Akter                   NaN              NaN  ...    Rajshahi        86.0     0.000000    A-
14    PH1015      Wahiduzzaman                  86.0             86.0  ...       Dhaka       256.0     0.904255     A
15    PH1016      Ziaur Rahman                  94.0             94.0  ...  Chattogram       274.0     1.000000    A+
16    PH1017       Afsana Mimi                  90.0             90.0  ...       Dhaka       273.0     0.994681    A+
17    PH1018       Babul Ahmed                  88.0             88.0  ...      Sylhet       261.0     0.930851    A+
18    PH1019      Faria Rahman                   NaN              NaN  ...  Chattogram        86.0     0.000000    A-
19    PH1020        Nasir Khan                  86.0             86.0  ...       Dhaka       261.0     0.930851    A+
20       NaN               NaN                   NaN              NaN  ...         NaN        86.0     0.000000    A-

[21 rows x 12 columns]

In [361]:
def marking_system(df): 
    a = df['Data Structure Marks'] * 2
    b = df['Python Marks'] * 3
    c = df['Algorithm Marks'] * 4

    return a+b+c

df['Exceptional Marks'] = df.apply(marking_system, axis=1)    # proccess by row,

df

   StudentID          FullName  Data Structure Marks  ...  Scaled Marks  Grade Exceptional Marks
0     PH1001       Alif Rahman                  85.0  ...      0.914894      A             774.0
1     PH1002     Fatima Akhter                  92.0  ...      0.978723     A+             810.0
2     PH1003     Imran Hossain                  88.0  ...      0.930851     A+             783.0
3     PH1004  Jannatul Ferdous                  78.0  ...      0.808511     A-             714.0
4     PH1005       Kamal Uddin                   NaN  ...      0.047872     A-               NaN
5     PH1006       Laila Begum                  75.0  ...      0.755319     A-             684.0
6     PH1007    Mahmudul Hasan                  80.0  ...      0.851064     A-             738.0
7     PH1008       Nadia Islam                  81.0  ...      0.856383     A-             741.0
8     PH1009        Omar Faruq                  72.0  ...      0.712766     A-             660.0
9     PH1010      Priya Sharma                  89.0  ...      0.957447     A+             798.0
10    PH1011      Rahim Sheikh                   NaN  ...      0.026596     A-               NaN
11    PH1012   Sadia Chowdhury                  85.0  ...      0.909574      A             771.0
12    PH1013      Tanvir Ahmed                  75.0  ...      0.760638     A-             687.0
13    PH1014        Urmi Akter                   NaN  ...      0.000000     A-               NaN
14    PH1015      Wahiduzzaman                  86.0  ...      0.904255      A             768.0
15    PH1016      Ziaur Rahman                  94.0  ...      1.000000     A+             822.0
16    PH1017       Afsana Mimi                  90.0  ...      0.994681     A+             819.0
17    PH1018       Babul Ahmed                  88.0  ...      0.930851     A+             783.0
18    PH1019      Faria Rahman                   NaN  ...      0.000000     A-               NaN
19    PH1020        Nasir Khan                  86.0  ...      0.930851     A+             783.0
20       NaN               NaN                   NaN  ...      0.000000     A-               NaN

[21 rows x 13 columns]

## datetime and time delta

In [362]:
df = pd.read_csv('student_completed_data.csv')
df

   StudentID          FullName CompletionStatus EnrollmentDate FinishedDate Instructor    Location  Total Marks
0     PH0001       Alif Rahman        Completed     2024-09-01   2024-12-23  Ms. Salma      Khulna          300
1     PH0002     Fatima Akhter        Completed     2024-08-11   2024-11-07  Mr. Karim       Dhaka          271
2     PH0003     Imran Hossain        Completed     2024-05-08   2024-08-08  Ms. Salma       Dhaka          269
3     PH0004  Jannatul Ferdous        Completed     2024-07-05   2024-09-23  Mr. Karim      Khulna          270
4     PH0005       Kamal Uddin        Completed     2024-02-01   2024-04-17  Mr. David      Sylhet          254
5     PH0006       Laila Begum        Completed     2024-09-07   2024-12-31  Mr. David      Khulna          272
6     PH0007    Mahmudul Hasan        Completed     2024-06-07   2024-07-20  Mr. David  Chattogram          249
7     PH0008       Nadia Islam        Completed     2024-03-22   2024-05-01  Ms. Salma      Khulna          246
8     PH0009        Omar Faruq        Completed     2024-02-12   2024-06-08  Mr. Karim       Dhaka          291
9     PH0010      Priya Sharma        Completed     2024-06-19   2024-08-19  Mr. David       Dhaka          286
10    PH0011      Rahim Sheikh        Completed     2024-03-14   2024-06-11  Mr. Karim      Sylhet          283
11    PH0012   Sadia Chowdhury        Completed     2024-08-04   2024-10-25  Mr. Karim      Sylhet          266
12    PH0013      Tanvir Ahmed        Completed     2024-06-07   2024-08-03  Mr. David       Dhaka          248
13    PH0014        Urmi Akter        Completed     2024-01-04   2024-03-23  Mr. David      Sylhet          285
14    PH0015      Wahiduzzaman        Completed     2024-02-22   2024-05-16  Mr. David    Rajshahi          291
15    PH0016      Ziaur Rahman        Completed     2024-03-23   2024-06-21  Ms. Salma    Rajshahi          234
16    PH0017       Afsana Mimi        Completed     2024-01-18   2024-03-16  Mr. David      Khulna          236
17    PH0018       Babul Ahmed        Completed     2024-06-23   2024-09-20  Mr. David       Dhaka          278
18    PH0019      Faria Rahman        Completed     2024-04-19   2024-08-17  Mr. Karim      Sylhet          277
19    PH0020       Tariq Hasan        Completed     2024-07-21   2024-10-11  Mr. Karim      Khulna          253

In [363]:
df['EnrollmentDate'] = pd.to_datetime(df['EnrollmentDate']) 

df['EnrollmentDate']

0    2024-09-01
1    2024-08-11
2    2024-05-08
3    2024-07-05
4    2024-02-01
5    2024-09-07
6    2024-06-07
7    2024-03-22
8    2024-02-12
9    2024-06-19
10   2024-03-14
11   2024-08-04
12   2024-06-07
13   2024-01-04
14   2024-02-22
15   2024-03-23
16   2024-01-18
17   2024-06-23
18   2024-04-19
19   2024-07-21
Name: EnrollmentDate, dtype: datetime64[ns]

In [364]:
df['Enrollment Year'] = df['EnrollmentDate'].dt.year

df

   StudentID          FullName CompletionStatus EnrollmentDate  ... Instructor    Location Total Marks  Enrollment Year
0     PH0001       Alif Rahman        Completed     2024-09-01  ...  Ms. Salma      Khulna         300             2024
1     PH0002     Fatima Akhter        Completed     2024-08-11  ...  Mr. Karim       Dhaka         271             2024
2     PH0003     Imran Hossain        Completed     2024-05-08  ...  Ms. Salma       Dhaka         269             2024
3     PH0004  Jannatul Ferdous        Completed     2024-07-05  ...  Mr. Karim      Khulna         270             2024
4     PH0005       Kamal Uddin        Completed     2024-02-01  ...  Mr. David      Sylhet         254             2024
5     PH0006       Laila Begum        Completed     2024-09-07  ...  Mr. David      Khulna         272             2024
6     PH0007    Mahmudul Hasan        Completed     2024-06-07  ...  Mr. David  Chattogram         249             2024
7     PH0008       Nadia Islam        Completed     2024-03-22  ...  Ms. Salma      Khulna         246             2024
8     PH0009        Omar Faruq        Completed     2024-02-12  ...  Mr. Karim       Dhaka         291             2024
9     PH0010      Priya Sharma        Completed     2024-06-19  ...  Mr. David       Dhaka         286             2024
10    PH0011      Rahim Sheikh        Completed     2024-03-14  ...  Mr. Karim      Sylhet         283             2024
11    PH0012   Sadia Chowdhury        Completed     2024-08-04  ...  Mr. Karim      Sylhet         266             2024
12    PH0013      Tanvir Ahmed        Completed     2024-06-07  ...  Mr. David       Dhaka         248             2024
13    PH0014        Urmi Akter        Completed     2024-01-04  ...  Mr. David      Sylhet         285             2024
14    PH0015      Wahiduzzaman        Completed     2024-02-22  ...  Mr. David    Rajshahi         291             2024
15    PH0016      Ziaur Rahman        Completed     2024-03-23  ...  Ms. Salma    Rajshahi         234             2024
16    PH0017       Afsana Mimi        Completed     2024-01-18  ...  Mr. David      Khulna         236             2024
17    PH0018       Babul Ahmed        Completed     2024-06-23  ...  Mr. David       Dhaka         278             2024
18    PH0019      Faria Rahman        Completed     2024-04-19  ...  Mr. Karim      Sylhet         277             2024
19    PH0020       Tariq Hasan        Completed     2024-07-21  ...  Mr. Karim      Khulna         253             2024

[20 rows x 9 columns]

In [365]:
df['Enrollment Month'] = df['EnrollmentDate'].dt.month

df

   StudentID          FullName CompletionStatus  ... Total Marks Enrollment Year Enrollment Month
0     PH0001       Alif Rahman        Completed  ...         300            2024                9
1     PH0002     Fatima Akhter        Completed  ...         271            2024                8
2     PH0003     Imran Hossain        Completed  ...         269            2024                5
3     PH0004  Jannatul Ferdous        Completed  ...         270            2024                7
4     PH0005       Kamal Uddin        Completed  ...         254            2024                2
5     PH0006       Laila Begum        Completed  ...         272            2024                9
6     PH0007    Mahmudul Hasan        Completed  ...         249            2024                6
7     PH0008       Nadia Islam        Completed  ...         246            2024                3
8     PH0009        Omar Faruq        Completed  ...         291            2024                2
9     PH0010      Priya Sharma        Completed  ...         286            2024                6
10    PH0011      Rahim Sheikh        Completed  ...         283            2024                3
11    PH0012   Sadia Chowdhury        Completed  ...         266            2024                8
12    PH0013      Tanvir Ahmed        Completed  ...         248            2024                6
13    PH0014        Urmi Akter        Completed  ...         285            2024                1
14    PH0015      Wahiduzzaman        Completed  ...         291            2024                2
15    PH0016      Ziaur Rahman        Completed  ...         234            2024                3
16    PH0017       Afsana Mimi        Completed  ...         236            2024                1
17    PH0018       Babul Ahmed        Completed  ...         278            2024                6
18    PH0019      Faria Rahman        Completed  ...         277            2024                4
19    PH0020       Tariq Hasan        Completed  ...         253            2024                7

[20 rows x 10 columns]

In [366]:
df['Enrollment Date'] = df['EnrollmentDate'].dt.day

df

   StudentID          FullName CompletionStatus  ... Enrollment Year Enrollment Month Enrollment Date
0     PH0001       Alif Rahman        Completed  ...            2024                9               1
1     PH0002     Fatima Akhter        Completed  ...            2024                8              11
2     PH0003     Imran Hossain        Completed  ...            2024                5               8
3     PH0004  Jannatul Ferdous        Completed  ...            2024                7               5
4     PH0005       Kamal Uddin        Completed  ...            2024                2               1
5     PH0006       Laila Begum        Completed  ...            2024                9               7
6     PH0007    Mahmudul Hasan        Completed  ...            2024                6               7
7     PH0008       Nadia Islam        Completed  ...            2024                3              22
8     PH0009        Omar Faruq        Completed  ...            2024                2              12
9     PH0010      Priya Sharma        Completed  ...            2024                6              19
10    PH0011      Rahim Sheikh        Completed  ...            2024                3              14
11    PH0012   Sadia Chowdhury        Completed  ...            2024                8               4
12    PH0013      Tanvir Ahmed        Completed  ...            2024                6               7
13    PH0014        Urmi Akter        Completed  ...            2024                1               4
14    PH0015      Wahiduzzaman        Completed  ...            2024                2              22
15    PH0016      Ziaur Rahman        Completed  ...            2024                3              23
16    PH0017       Afsana Mimi        Completed  ...            2024                1              18
17    PH0018       Babul Ahmed        Completed  ...            2024                6              23
18    PH0019      Faria Rahman        Completed  ...            2024                4              19
19    PH0020       Tariq Hasan        Completed  ...            2024                7              21

[20 rows x 11 columns]

In [367]:
df['FinishedDate'] = pd.to_datetime(df['FinishedDate'])

df['FinishedDate']

0    2024-12-23
1    2024-11-07
2    2024-08-08
3    2024-09-23
4    2024-04-17
5    2024-12-31
6    2024-07-20
7    2024-05-01
8    2024-06-08
9    2024-08-19
10   2024-06-11
11   2024-10-25
12   2024-08-03
13   2024-03-23
14   2024-05-16
15   2024-06-21
16   2024-03-16
17   2024-09-20
18   2024-08-17
19   2024-10-11
Name: FinishedDate, dtype: datetime64[ns]

In [368]:
df['Finish Time'] = df['FinishedDate'] - df['EnrollmentDate']

df

   StudentID          FullName CompletionStatus  ... Enrollment Month Enrollment Date Finish Time
0     PH0001       Alif Rahman        Completed  ...                9               1    113 days
1     PH0002     Fatima Akhter        Completed  ...                8              11     88 days
2     PH0003     Imran Hossain        Completed  ...                5               8     92 days
3     PH0004  Jannatul Ferdous        Completed  ...                7               5     80 days
4     PH0005       Kamal Uddin        Completed  ...                2               1     76 days
5     PH0006       Laila Begum        Completed  ...                9               7    115 days
6     PH0007    Mahmudul Hasan        Completed  ...                6               7     43 days
7     PH0008       Nadia Islam        Completed  ...                3              22     40 days
8     PH0009        Omar Faruq        Completed  ...                2              12    117 days
9     PH0010      Priya Sharma        Completed  ...                6              19     61 days
10    PH0011      Rahim Sheikh        Completed  ...                3              14     89 days
11    PH0012   Sadia Chowdhury        Completed  ...                8               4     82 days
12    PH0013      Tanvir Ahmed        Completed  ...                6               7     57 days
13    PH0014        Urmi Akter        Completed  ...                1               4     79 days
14    PH0015      Wahiduzzaman        Completed  ...                2              22     84 days
15    PH0016      Ziaur Rahman        Completed  ...                3              23     90 days
16    PH0017       Afsana Mimi        Completed  ...                1              18     58 days
17    PH0018       Babul Ahmed        Completed  ...                6              23     89 days
18    PH0019      Faria Rahman        Completed  ...                4              19    120 days
19    PH0020       Tariq Hasan        Completed  ...                7              21     82 days

[20 rows x 12 columns]

## Groupby

In [369]:
df.drop(columns=['StudentID','FullName','CompletionStatus', 'EnrollmentDate', 'FinishedDate'], inplace=True)

In [370]:
group = df.groupby('Instructor')

In [371]:
group.sum()

                                                     Location  Total Marks  ...  Enrollment Date  Finish Time
Instructor                                                                  ...
Mr. David   SylhetKhulnaChattogramDhakaDhakaSylhetRajshahi...         2399  ...              108     662 days
Mr. Karim            DhakaKhulnaDhakaSylhetSylhetSylhetKhulna         1911  ...               86     658 days
Ms. Salma                           KhulnaDhakaKhulnaRajshahi         1049  ...               54     335 days

[3 rows x 6 columns]

In [372]:
group.min()

              Location  Total Marks  Enrollment Year  Enrollment Month  Enrollment Date Finish Time
Instructor
Mr. David   Chattogram          236             2024                 1                1     43 days
Mr. Karim        Dhaka          253             2024                 2                4     80 days
Ms. Salma        Dhaka          234             2024                 3                1     40 days

In [373]:
group.max()

            Location  Total Marks  Enrollment Year  Enrollment Month  Enrollment Date Finish Time
Instructor
Mr. David     Sylhet          291             2024                 9               23    115 days
Mr. Karim     Sylhet          291             2024                 8               21    120 days
Ms. Salma   Rajshahi          300             2024                 9               23    113 days

In [374]:
group.first()

           Location  Total Marks  Enrollment Year  Enrollment Month  Enrollment Date Finish Time
Instructor
Mr. David    Sylhet          254             2024                 2                1     76 days
Mr. Karim     Dhaka          271             2024                 8               11     88 days
Ms. Salma    Khulna          300             2024                 9                1    113 days

In [375]:
group.last()

            Location  Total Marks  Enrollment Year  Enrollment Month  Enrollment Date Finish Time
Instructor
Mr. David      Dhaka          278             2024                 6               23     89 days
Mr. Karim     Khulna          253             2024                 7               21     82 days
Ms. Salma   Rajshahi          234             2024                 3               23     90 days

In [376]:
df.sort_values('Total Marks', ascending=False).groupby('Instructor').head(5)

   Instructor  Location  Total Marks  Enrollment Year  Enrollment Month  Enrollment Date Finish Time
0   Ms. Salma    Khulna          300             2024                 9                1    113 days
8   Mr. Karim     Dhaka          291             2024                 2               12    117 days
14  Mr. David  Rajshahi          291             2024                 2               22     84 days
9   Mr. David     Dhaka          286             2024                 6               19     61 days
13  Mr. David    Sylhet          285             2024                 1                4     79 days
10  Mr. Karim    Sylhet          283             2024                 3               14     89 days
17  Mr. David     Dhaka          278             2024                 6               23     89 days
18  Mr. Karim    Sylhet          277             2024                 4               19    120 days
5   Mr. David    Khulna          272             2024                 9                7    115 days
1   Mr. Karim     Dhaka          271             2024                 8               11     88 days
3   Mr. Karim    Khulna          270             2024                 7                5     80 days
2   Ms. Salma     Dhaka          269             2024                 5                8     92 days
7   Ms. Salma    Khulna          246             2024                 3               22     40 days
15  Ms. Salma  Rajshahi          234             2024                 3               23     90 days

In [377]:
df = pd.read_csv('student_completed_data.csv')
df

   StudentID          FullName CompletionStatus EnrollmentDate FinishedDate Instructor    Location  Total Marks
0     PH0001       Alif Rahman        Completed     2024-09-01   2024-12-23  Ms. Salma      Khulna          300
1     PH0002     Fatima Akhter        Completed     2024-08-11   2024-11-07  Mr. Karim       Dhaka          271
2     PH0003     Imran Hossain        Completed     2024-05-08   2024-08-08  Ms. Salma       Dhaka          269
3     PH0004  Jannatul Ferdous        Completed     2024-07-05   2024-09-23  Mr. Karim      Khulna          270
4     PH0005       Kamal Uddin        Completed     2024-02-01   2024-04-17  Mr. David      Sylhet          254
5     PH0006       Laila Begum        Completed     2024-09-07   2024-12-31  Mr. David      Khulna          272
6     PH0007    Mahmudul Hasan        Completed     2024-06-07   2024-07-20  Mr. David  Chattogram          249
7     PH0008       Nadia Islam        Completed     2024-03-22   2024-05-01  Ms. Salma      Khulna          246
8     PH0009        Omar Faruq        Completed     2024-02-12   2024-06-08  Mr. Karim       Dhaka          291
9     PH0010      Priya Sharma        Completed     2024-06-19   2024-08-19  Mr. David       Dhaka          286
10    PH0011      Rahim Sheikh        Completed     2024-03-14   2024-06-11  Mr. Karim      Sylhet          283
11    PH0012   Sadia Chowdhury        Completed     2024-08-04   2024-10-25  Mr. Karim      Sylhet          266
12    PH0013      Tanvir Ahmed        Completed     2024-06-07   2024-08-03  Mr. David       Dhaka          248
13    PH0014        Urmi Akter        Completed     2024-01-04   2024-03-23  Mr. David      Sylhet          285
14    PH0015      Wahiduzzaman        Completed     2024-02-22   2024-05-16  Mr. David    Rajshahi          291
15    PH0016      Ziaur Rahman        Completed     2024-03-23   2024-06-21  Ms. Salma    Rajshahi          234
16    PH0017       Afsana Mimi        Completed     2024-01-18   2024-03-16  Mr. David      Khulna          236
17    PH0018       Babul Ahmed        Completed     2024-06-23   2024-09-20  Mr. David       Dhaka          278
18    PH0019      Faria Rahman        Completed     2024-04-19   2024-08-17  Mr. Karim      Sylhet          277
19    PH0020       Tariq Hasan        Completed     2024-07-21   2024-10-11  Mr. Karim      Khulna          253

In [378]:
df['Total Marks'] > 250

0      True
1      True
2      True
3      True
4      True
5      True
6     False
7     False
8      True
9      True
10     True
11     True
12    False
13     True
14     True
15    False
16    False
17     True
18     True
19     True
Name: Total Marks, dtype: bool

In [380]:
(df['Total Marks'] > 250).sum()

np.int64(15)