In [181]:
import pandas as pd

## problem 1

In [182]:
lst = [10, 20, 30, 40, 50]

series = pd.Series(lst)

print(series)

print(series.index)

print(type(series))

0    10
1    20
2    30
3    40
4    50
dtype: int64
RangeIndex(start=0, stop=5, step=1)
<class 'pandas.core.series.Series'>

In [183]:
lst = [['Karim', 30, 'Dhaka'], ['Rahim', 28, 'Noakhali'], ['Fahim', 25, 'Sylhet'], ['Rafiq', 35, 'Chittagong']]

df = pd.DataFrame(lst, columns=['Name', 'Age', 'City'], index=[1,2,3,4])

## problem 2

In [184]:
df

    Name  Age        City
1  Karim   30       Dhaka
2  Rahim   28    Noakhali
3  Fahim   25      Sylhet
4  Rafiq   35  Chittagong

In [185]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, 1 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   City    4 non-null      object
dtypes: int64(1), object(2)
memory usage: 128.0+ bytes

In [186]:
df.describe()

             Age
count   4.000000
mean   29.500000
std     4.203173
min    25.000000
25%    27.250000
50%    29.000000
75%    31.250000
max    35.000000

In [187]:
df.shape

(4, 3)

In [188]:
df.count()

Name    4
Age     4
City    4
dtype: int64

In [189]:
df.dtypes

Name    object
Age      int64
City    object
dtype: object

## problem 3

In [190]:
data = {
    'Product': ['Pen', 'Book', 'Eraser', 'Pencil'],
    'Price': [10, 50, 5, 7],
    'Quantity': [100, 60, 200, 150]
}

df = pd.DataFrame(data)

df

  Product  Price  Quantity
0     Pen     10       100
1    Book     50        60
2  Eraser      5       200
3  Pencil      7       150

In [191]:
df.columns

Index(['Product', 'Price', 'Quantity'], dtype='object')

In [192]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [193]:
df['Product']

0       Pen
1      Book
2    Eraser
3    Pencil
Name: Product, dtype: object

In [194]:
df.loc[1]

Product     Book
Price         50
Quantity      60
Name: 1, dtype: object

## problem 4

In [195]:
df.loc[:,'Price']

0    10
1    50
2     5
3     7
Name: Price, dtype: int64

In [196]:
df.loc[1,'Price']

np.int64(50)

In [197]:
middle = df.iloc[1:3, 0:2]

middle

  Product  Price
1    Book     50
2  Eraser      5

## problem 5

In [198]:
data = {
    'Student Name': ['Abir', 'Tasin', 'Sami', 'Irfan'],
    'Math Marks': [96, 97, 88, 77],
    'English Marks': [100, 60, 200, 150]
}

df = pd.DataFrame(data)

df.shape

df

  Student Name  Math Marks  English Marks
0         Abir          96            100
1        Tasin          97             60
2         Sami          88            200
3        Irfan          77            150

In [199]:
drop_row = df.drop(1)
drop_row

  Student Name  Math Marks  English Marks
0         Abir          96            100
2         Sami          88            200
3        Irfan          77            150

In [200]:
drop_col = df.drop('English Marks', axis=1)
drop_col

  Student Name  Math Marks
0         Abir          96
1        Tasin          97
2         Sami          88
3        Irfan          77

## problem 6

In [201]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "Diana"],
    "Department": ["HR", "Engineering", "Finance", "Marketing"],
    "Salary": [55000, 72000, 68000, 59000]
}

df = pd.DataFrame(data)
print(df)

      Name   Department  Salary
0    Alice           HR   55000
1      Bob  Engineering   72000
2  Charlie      Finance   68000
3    Diana    Marketing   59000

In [202]:
sort = df.sort_values(['Salary','Name'], ascending=[1,0])

sort

      Name   Department  Salary
0    Alice           HR   55000
3    Diana    Marketing   59000
2  Charlie      Finance   68000
1      Bob  Engineering   72000

## problem 7

In [203]:
data = {
    "Name": [
        "Alice", "Bob", "Charlie", "Diana",
        "Evan", "Fiona", "George", "Hannah"
    ],
    "Score": [88, 74, 77, 55, 85, 49, 33, 72]
}

df = pd.DataFrame(data)
print(df)

      Name  Score
0    Alice     88
1      Bob     74
2  Charlie     77
3    Diana     55
4     Evan     85
5    Fiona     49
6   George     33
7   Hannah     72

In [204]:
df.loc[(df['Score'] > 60)]

      Name  Score
0    Alice     88
1      Bob     74
2  Charlie     77
4     Evan     85
7   Hannah     72

In [205]:
df.loc[(df['Score'] < 40)]

     Name  Score
6  George     33

In [206]:
df.loc[(df['Score'] > 60) | (df['Score'] < 40)]

      Name  Score
0    Alice     88
1      Bob     74
2  Charlie     77
4     Evan     85
6   George     33
7   Hannah     72